/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Button: typeof import('./../components/ui/Button.vue')['default']
    Checkbox: typeof import('./../components/ui/Checkbox.vue')['default']
    Flex: typeof import('./../components/core/Flex.vue')['default']
    Header: typeof import('./../components/Header.vue')['default']
    Icon: typeof import('./../components/core/Icon.vue')['default']
    Input: typeof import('./../components/ui/Input.vue')['default']
    Install: typeof import('./../components/install.vue')['default']
    LogoStar: typeof import('./../components/LogoStar.vue')['default']
    Or: typeof import('./../components/Or.vue')['default']
    Popup: typeof import('./../components/ui/Popup/Popup.vue')['default']
    PopupCard: typeof import('./../components/ui/Popup/PopupCard.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Text: typeof import('./../components/core/Text.vue')['default']
    Toggle: typeof import('./../components/ui/Toggle.vue')['default']
    Tooltip: typeof import('./../components/ui/Tooltip.vue')['default']
    Update: typeof import('./../components/update.vue')['default']
  }
}
