/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Badge: typeof import('./../components/ui/Badge.vue')['default']
    Banner: typeof import('./../components/ui/Banner.vue')['default']
    Breadcrumbs: typeof import('./../components/ui/Settings/Breadcrumbs.vue')['default']
    Button: typeof import('./../components/ui/Button.vue')['default']
    Checkbox: typeof import('./../components/ui/Checkbox.vue')['default']
    Divider: typeof import('./../components/Divider.vue')['default']
    DropdownDivider: typeof import('./../components/ui/Dropdown/DropdownDivider.vue')['default']
    DropdownItem: typeof import('./../components/ui/Dropdown/DropdownItem.vue')['default']
    DropdownRoot: typeof import('./../components/ui/Dropdown/DropdownRoot.vue')['default']
    DropdownTitle: typeof import('./../components/ui/Dropdown/DropdownTitle.vue')['default']
    DropdownTrigger: typeof import('./../components/ui/Dropdown/DropdownTrigger.vue')['default']
    Flex: typeof import('./../components/core/Flex.vue')['default']
    GlobalLoader: typeof import('./../components/ui/GlobalLoader.vue')['default']
    Header: typeof import('./../components/Header.vue')['default']
    Icon: typeof import('./../components/core/Icon.vue')['default']
    Input: typeof import('./../components/ui/Input.vue')['default']
    Install: typeof import('./../components/install.vue')['default']
    ItemsContainer: typeof import('./../components/ui/Settings/ItemsContainer.vue')['default']
    JsonViewer: typeof import('./../components/ui/JsonViewer/JsonViewer.vue')['default']
    LogoStar: typeof import('./../components/LogoStar.vue')['default']
    LogsViewer: typeof import('./../components/ui/JsonViewer/LogsViewer.vue')['default']
    NotificationManager: typeof import('./../components/ui/NotificationManager.vue')['default']
    PageHeader: typeof import('./../components/ui/Settings/PageHeader.vue')['default']
    Popover: typeof import('./../components/ui/Popover.vue')['default']
    Popup: typeof import('./../components/ui/Popup/Popup.vue')['default']
    PopupCard: typeof import('./../components/ui/Popup/PopupCard.vue')['default']
    PopupHeader: typeof import('./../components/ui/Popup/PopupHeader.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SettingField: typeof import('./../components/ui/Settings/SettingField.vue')['default']
    SettingItem: typeof import('./../components/ui/Settings/SettingItem.vue')['default']
    SettingValue: typeof import('./../components/ui/Settings/SettingValue.vue')['default']
    Spinner: typeof import('./../components/ui/Spinner.vue')['default']
    Text: typeof import('./../components/core/Text.vue')['default']
    ToastManager: typeof import('./../components/ui/ToastManager.vue')['default']
    Toggle: typeof import('./../components/ui/Toggle.vue')['default']
    Tooltip: typeof import('./../components/ui/Tooltip.vue')['default']
    Update: typeof import('./../components/update.vue')['default']
  }
}
